# Generated by Django 5.0.7 on 2025-02-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
